version: '3'

tasks:
  up:
    dir: '{{.USER_WORKING_DIR}}'
    preconditions:
      - echo "checking pre-conditions"
    cmds:
      - docker-compose down -v
      - docker-compose up --build

  down:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - docker-compose down -v