version: '3'

tasks:
  up:
    dir: '{{.USER_WORKING_DIR}}'
    preconditions:
      - test -f docker-compose.yml
    cmds:
      - docker-compose down -f stack.yml -v
      - docker-compose up -f stack.yml --build

  down:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - docker-compose down -f stack.yml -v